package com.gym.management.config;

import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@Configuration
public class SchemaFixConfig {

    private static final Logger logger = LoggerFactory.getLogger(SchemaFixConfig.class);

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @PostConstruct
    public void fixSchema() {
        // ── existing fix ──────────────────────────────────────────────────────
        try {
            jdbcTemplate.execute("ALTER TABLE message_attachments MODIFY (message_id NULL)");
            logger.info("Schema fix: message_attachments.message_id set nullable.");
        } catch (Exception e) {
            logger.warn("Schema fix warning (might be already applied): " + e.getMessage());
        }

        // ── trainer_requests table (create if not exists) ─────────────────────
        // Oracle has no CREATE TABLE IF NOT EXISTS before 23c, so we check first.
        try {
            Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM user_tables WHERE table_name = 'TRAINER_REQUESTS'",
                Integer.class);
            if (count == null || count == 0) {
                logger.info("Creating trainer_requests table...");
                jdbcTemplate.execute(
                    "CREATE TABLE trainer_requests (" +
                    "  id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "  member_id      NUMBER NOT NULL," +
                    "  trainer_id     NUMBER NOT NULL," +
                    "  status         VARCHAR2(20) DEFAULT 'PENDING' NOT NULL," +
                    "  member_message CLOB," +
                    "  trainer_note   CLOB," +
                    "  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                    "  resolved_at    TIMESTAMP," +
                    "  CONSTRAINT fk_tr_member  FOREIGN KEY (member_id)  REFERENCES users(user_id)," +
                    "  CONSTRAINT fk_tr_trainer FOREIGN KEY (trainer_id) REFERENCES users(user_id)" +
                    ")"
                );
                logger.info("trainer_requests table created successfully.");
            } else {
                logger.info("trainer_requests table already exists — skipping creation.");
            }
        } catch (Exception e) {
            logger.error("Failed to create trainer_requests table: " + e.getMessage(), e);
        }
    }
}
