SET SERVEROUTPUT ON FEEDBACK OFF
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE notifications RENAME COLUMN notification_id TO id';
    DBMS_OUTPUT.PUT_LINE('Renamed NOTIFICATION_ID to ID in NOTIFICATIONS');
EXCEPTION WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/
SELECT column_name, data_type FROM user_tab_columns WHERE table_name = 'NOTIFICATIONS' AND column_name IN ('ID','NOTIFICATION_ID') ORDER BY column_id;
EXIT;