-- Add profile fields to users table (Oracle syntax)
ALTER TABLE users ADD (
    date_of_birth DATE,
    gender VARCHAR2(20),
    blood_type VARCHAR2(10),
    address VARCHAR2(500),
    city VARCHAR2(100),
    state VARCHAR2(100),
    zip_code VARCHAR2(20),
    emergency_contact_name VARCHAR2(255),
    emergency_contact_phone VARCHAR2(50),
    health_notes CLOB,
    fitness_goals CLOB,
    height NUMBER(5,2),
    weight NUMBER(5,2),
    body_fat NUMBER(4,2),
    two_factor_enabled NUMBER(1) DEFAULT 0
);

CREATE TABLE workout_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    workout_date DATE NOT NULL,
    duration_minutes NUMBER,
    workout_type VARCHAR2(100),
    notes CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_workout_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE member_achievements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    achievement_type VARCHAR2(100) NOT NULL,
    achievement_name VARCHAR2(255) NOT NULL,
    description CLOB,
    earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_achievement_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE member_body_stats_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    height NUMBER(5,2),
    weight NUMBER(5,2),
    body_fat NUMBER(4,2),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_body_stats_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE INDEX idx_workout_logs_user_id ON workout_logs(user_id);
CREATE INDEX idx_workout_logs_date ON workout_logs(workout_date);
CREATE INDEX idx_achievements_user_id ON member_achievements(user_id);
CREATE INDEX idx_body_stats_user_id ON member_body_stats_history(user_id);
