-- Create trainer_classes table
CREATE TABLE trainer_classes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    trainer_id NUMBER NOT NULL,
    class_date DATE NOT NULL,
    start_time VARCHAR2(10) NOT NULL,
    end_time VARCHAR2(10) NOT NULL,
    duration NUMBER NOT NULL,
    room VARCHAR2(50),
    capacity NUMBER DEFAULT 20,
    enrolled NUMBER DEFAULT 0,
    class_type VARCHAR2(20) DEFAULT 'GROUP',
    status VARCHAR2(20) DEFAULT 'UPCOMING',
    is_recurring NUMBER(1) DEFAULT 0,
    notes VARCHAR2(500),
    CONSTRAINT fk_trainer_class_trainer FOREIGN KEY (trainer_id) REFERENCES users(user_id)
);

-- Create trainer_class_attendees table
CREATE TABLE trainer_class_attendees (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING',
    CONSTRAINT fk_attendee_class FOREIGN KEY (class_id) REFERENCES trainer_classes(id),
    CONSTRAINT fk_attendee_member FOREIGN KEY (member_id) REFERENCES users(user_id)
);

-- Create indexes
CREATE INDEX idx_trainer_classes_trainer ON trainer_classes(trainer_id);
CREATE INDEX idx_trainer_classes_date ON trainer_classes(class_date);
CREATE INDEX idx_class_attendees_class ON trainer_class_attendees(class_id);

-- Insert mock data for trainer ID 1 (today = SYSDATE)
-- Using SYSDATE for dynamic dates
INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('Morning Yoga', 1, TRUNC(SYSDATE), '06:00', '07:00', 60, 'Studio A', 15, 12, 'GROUP', 'COMPLETED', 1, NULL);

INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('HIIT Burn', 1, TRUNC(SYSDATE), '08:30', '09:30', 60, 'Main Floor', 20, 18, 'GROUP', 'IN_PROGRESS', 1, NULL);

INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('PT - Sarah Wilson', 1, TRUNC(SYSDATE), '10:00', '11:00', 60, 'PT Area', 1, 1, 'PT', 'UPCOMING', 0, 'Focus on lower body strength');

INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('Spin Class', 1, TRUNC(SYSDATE), '12:00', '12:45', 45, 'Spin Studio', 20, 20, 'GROUP', 'UPCOMING', 1, NULL);

INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('PT - Mike Johnson', 1, TRUNC(SYSDATE), '14:00', '15:00', 60, 'PT Area', 1, 1, 'PT', 'UPCOMING', 0, 'Recovery session after injury');

INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('Evening Pilates', 1, TRUNC(SYSDATE), '17:30', '18:30', 60, 'Studio B', 12, 8, 'GROUP', 'UPCOMING', 1, NULL);

INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('Strength Training', 1, TRUNC(SYSDATE), '19:00', '20:00', 60, 'Weight Room', 15, 10, 'GROUP', 'CANCELLED', 1, NULL);

-- Tomorrow's classes
INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('Advanced HIIT', 1, TRUNC(SYSDATE) + 1, '07:00', '08:00', 60, 'Main Floor', 20, 15, 'GROUP', 'UPCOMING', 1, NULL);

INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('PT - Emma Davis', 1, TRUNC(SYSDATE) + 1, '09:00', '10:00', 60, 'PT Area', 1, 1, 'PT', 'UPCOMING', 0, NULL);

-- Day after tomorrow
INSERT INTO trainer_classes (title, trainer_id, class_date, start_time, end_time, duration, room, capacity, enrolled, class_type, status, is_recurring, notes)
VALUES ('Cardio Blast', 1, TRUNC(SYSDATE) + 2, '18:00', '19:00', 60, 'Main Floor', 25, 22, 'GROUP', 'UPCOMING', 1, NULL);

-- Insert attendees for classes
-- Class 1 (Morning Yoga - completed): 11 confirmed, 1 absent
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 2, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 3, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 4, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 5, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 6, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 7, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 8, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 9, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 10, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 11, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 12, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (1, 13, 'ABSENT');

-- Class 2 (HIIT Burn - in-progress): 16 confirmed, 2 pending
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 2, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 3, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 4, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 5, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 6, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 7, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 8, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 9, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 10, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 11, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 12, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 13, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 14, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 15, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 16, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 17, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 18, 'PENDING');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (2, 19, 'PENDING');

-- Class 3 (PT Session): 1 confirmed
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (3, 2, 'CONFIRMED');

-- Class 4 (Spin Class): 15 confirmed, 5 pending
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 3, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 4, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 5, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 6, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 7, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 8, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 9, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 10, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 11, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 12, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 13, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 14, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 15, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 16, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 17, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 18, 'PENDING');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 19, 'PENDING');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 20, 'PENDING');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 21, 'PENDING');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (4, 22, 'PENDING');

-- Class 5 (PT with Mike): 1 pending
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (5, 5, 'PENDING');

-- Class 6 (Pilates): 6 confirmed, 2 pending
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 2, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 3, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 4, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 5, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 6, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 7, 'CONFIRMED');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 8, 'PENDING');
INSERT INTO trainer_class_attendees (class_id, member_id, status) VALUES (6, 9, 'PENDING');
