-- =========================================
-- V14__create_tiered_membership_plans.sql
-- Creates new tiered membership plan architecture
-- MembershipPlan -> PlanVariant (One-to-Many)
-- MembershipPlan -> PlanFeature (One-to-Many)
-- =========================================

-- =========================================
-- 1. MEMBERSHIP_PLANS - Parent plan entity
-- =========================================
CREATE TABLE membership_plans (
    plan_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR2(100) NOT NULL,
    description VARCHAR2(500),
    category VARCHAR2(20) DEFAULT 'STANDARD' NOT NULL,
    plan_color VARCHAR2(7),
    icon_name VARCHAR2(50),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    is_recommended NUMBER(1) DEFAULT 0,
    sort_order NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_plan_category CHECK (category IN ('STANDARD', 'PREMIUM', 'VIP', 'CORPORATE', 'STUDENT', 'CUSTOM')),
    CONSTRAINT chk_plan_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED')),
    CONSTRAINT uk_membership_plan_name UNIQUE (plan_name)
);

-- =========================================
-- 2. PLAN_VARIANTS - Duration/Price options
-- =========================================
CREATE TABLE plan_variants (
    variant_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    plan_id NUMBER NOT NULL,
    duration_value NUMBER NOT NULL,
    duration_unit VARCHAR2(10) DEFAULT 'MONTHS' NOT NULL,
    duration_days NUMBER NOT NULL,
    price NUMBER(10,2) NOT NULL,
    original_price NUMBER(10,2),
    discount_percent NUMBER(5,2),
    included_pt_sessions NUMBER DEFAULT 0,
    is_popular NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1,
    sort_order NUMBER DEFAULT 0,
    
    CONSTRAINT fk_variant_plan FOREIGN KEY (plan_id) 
        REFERENCES membership_plans(plan_id) ON DELETE CASCADE,
    CONSTRAINT chk_duration_unit CHECK (duration_unit IN ('DAYS', 'WEEKS', 'MONTHS', 'YEARS')),
    CONSTRAINT chk_variant_price CHECK (price > 0),
    CONSTRAINT chk_variant_duration CHECK (duration_value > 0),
    CONSTRAINT uk_plan_variant_duration UNIQUE (plan_id, duration_value, duration_unit)
);

-- =========================================
-- 3. PLAN_FEATURES - Amenities/Access items
-- =========================================
CREATE TABLE plan_features (
    feature_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    plan_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(255),
    category VARCHAR2(20) DEFAULT 'ACCESS' NOT NULL,
    is_included NUMBER(1) DEFAULT 1,
    sort_order NUMBER DEFAULT 0,
    
    CONSTRAINT fk_feature_plan FOREIGN KEY (plan_id) 
        REFERENCES membership_plans(plan_id) ON DELETE CASCADE,
    CONSTRAINT chk_feature_category CHECK (category IN ('ACCESS', 'EQUIPMENT', 'CLASSES', 'AMENITIES', 'SERVICES', 'PERKS'))
);

-- =========================================
-- 4. INDEXES for performance
-- =========================================
CREATE INDEX idx_plan_variants_plan_id ON plan_variants(plan_id);
CREATE INDEX idx_plan_variants_active ON plan_variants(is_active);
CREATE INDEX idx_plan_features_plan_id ON plan_features(plan_id);
CREATE INDEX idx_membership_plans_status ON membership_plans(status);
CREATE INDEX idx_membership_plans_category ON membership_plans(category);

-- =========================================
-- 5. TRIGGER for updated_at timestamp
-- =========================================
CREATE OR REPLACE TRIGGER trg_membership_plans_updated
BEFORE UPDATE ON membership_plans
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
