CREATE TABLE trainer_settings (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19,0) NOT NULL UNIQUE,
    notification_prefs CLOB,
    privacy_prefs CLOB,
    appearance_prefs CLOB,
    regional_prefs CLOB,
    updated_at TIMESTAMP,
    CONSTRAINT fk_trainer_settings_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Index for faster lookups by user_id
CREATE INDEX idx_trainer_settings_user ON trainer_settings(user_id);
