-- =========================================
-- V15__create_audit_log_tables.sql
-- Creates audit_logs and updates user_sessions
-- Enterprise-grade audit logging system
-- =========================================

-- =========================================
-- 1. AUDIT_LOGS - System audit trail
-- =========================================
CREATE TABLE audit_logs (
    audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    action VARCHAR2(100) NOT NULL,
    entity VARCHAR2(100),
    entity_id VARCHAR2(100),
    entity_name VARCHAR2(255),
    target VARCHAR2(255),
    user_name VARCHAR2(100),
    user_role VARCHAR2(50),
    user_avatar VARCHAR2(500),
    details CLOB,
    changes CLOB,
    ip_address VARCHAR2(50),
    location VARCHAR2(255),
    device_type VARCHAR2(50),
    browser VARCHAR2(100),
    os VARCHAR2(100),
    session_id VARCHAR2(100),
    severity VARCHAR2(20) DEFAULT 'info',
    metadata CLOB,
    timestamp TIMESTAMP NOT NULL,
    user_id NUMBER,
    gym_id NUMBER,
    
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_audit_gym FOREIGN KEY (gym_id) REFERENCES gyms(gym_id)
);

-- =========================================
-- 2. INDEXES for audit_logs
-- =========================================
CREATE INDEX idx_audit_timestamp ON audit_logs(timestamp);
CREATE INDEX idx_audit_action ON audit_logs(action);
CREATE INDEX idx_audit_entity ON audit_logs(entity);
CREATE INDEX idx_audit_severity ON audit_logs(severity);
CREATE INDEX idx_audit_user_id ON audit_logs(user_id);
CREATE INDEX idx_audit_gym_id ON audit_logs(gym_id);

-- =========================================
-- 3. USER_SESSIONS - Session tracking
-- (Only run if table doesn't exist)
-- =========================================
CREATE TABLE user_sessions (
    session_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    gym_id NUMBER,
    token_hash VARCHAR2(256) NOT NULL,
    status VARCHAR2(20) DEFAULT 'online',
    device VARCHAR2(255),
    device_type VARCHAR2(50),
    browser VARCHAR2(100),
    os VARCHAR2(100),
    ip_address VARCHAR2(50),
    location VARCHAR2(255),
    user_agent CLOB,
    created_at TIMESTAMP NOT NULL,
    last_active_at TIMESTAMP,
    logout_at TIMESTAMP,
    expires_at TIMESTAMP,
    duration NUMBER,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    
    CONSTRAINT fk_session_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_session_gym FOREIGN KEY (gym_id) REFERENCES gyms(gym_id)
);

-- =========================================
-- 4. INDEXES for user_sessions
-- =========================================
CREATE INDEX idx_session_user_id ON user_sessions(user_id);
CREATE INDEX idx_session_gym_id ON user_sessions(gym_id);
CREATE INDEX idx_session_status ON user_sessions(status);
CREATE INDEX idx_session_active ON user_sessions(is_active);

-- =========================================
-- 5. Seed initial audit log entry
-- =========================================
INSERT INTO audit_logs (action, entity, details, severity, timestamp, user_name, user_role)
VALUES ('SYSTEM_INIT', 'System', 'Audit logging system initialized', 'info', CURRENT_TIMESTAMP, 'System', 'SYSTEM');
