-- =========================================
-- V16__enhance_audit_logging_system.sql
-- Enhanced audit logging with micro-level tracking
-- =========================================

-- =========================================
-- 1. ENHANCED AUDIT LOGS TABLE
-- =========================================
-- Add new columns for enhanced tracking
ALTER TABLE audit_logs ADD (
    method_name VARCHAR2(200),
    class_name VARCHAR2(200),
    execution_time NUMBER(10),
    stack_trace CLOB,
    request_id VARCHAR2(100),
    correlation_id VARCHAR2(100),
    business_impact VARCHAR2(50) DEFAULT 'low',
    data_classification VARCHAR2(50) DEFAULT 'internal',
    retention_period NUMBER(3) DEFAULT 365,
    encrypted_fields CLOB,
    tags CLOB
);

-- =========================================
-- 2. AUDIT LOG CHANGE DETAILS TABLE
-- =========================================
CREATE TABLE audit_log_changes (
    change_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    audit_id NUMBER NOT NULL,
    field_name VARCHAR2(100) NOT NULL,
    field_type VARCHAR2(50),
    old_value CLOB,
    new_value CLOB,
    change_type VARCHAR2(20) NOT NULL, -- 'modified', 'added', 'removed'
    is_sensitive CHAR(1) DEFAULT 'N',
    data_classification VARCHAR2(50),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_audit_change FOREIGN KEY (audit_id) REFERENCES audit_logs(audit_id) ON DELETE CASCADE
);

-- =========================================
-- 3. AUDIT LOG METRICS TABLE
-- =========================================
CREATE TABLE audit_log_metrics (
    metric_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    audit_id NUMBER NOT NULL,
    metric_name VARCHAR2(100) NOT NULL,
    metric_value NUMBER(15,2),
    metric_unit VARCHAR2(20),
    threshold_value NUMBER(15,2),
    is_violation CHAR(1) DEFAULT 'N',
    
    CONSTRAINT fk_audit_metric FOREIGN KEY (audit_id) REFERENCES audit_logs(audit_id) ON DELETE CASCADE
);

-- =========================================
-- 4. AUDIT LOG BUSINESS CONTEXT
-- =========================================
CREATE TABLE audit_business_context (
    context_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    audit_id NUMBER NOT NULL,
    business_process VARCHAR2(100),
    business_entity VARCHAR2(100),
    business_rule VARCHAR2(200),
    compliance_requirement VARCHAR2(100),
    risk_level VARCHAR2(20),
    approval_required CHAR(1) DEFAULT 'N',
    
    CONSTRAINT fk_audit_context FOREIGN KEY (audit_id) REFERENCES audit_logs(audit_id) ON DELETE CASCADE
);

-- =========================================
-- 5. ENHANCED INDEXES
-- =========================================
CREATE INDEX idx_audit_method ON audit_logs(method_name);
CREATE INDEX idx_audit_class ON audit_logs(class_name);
CREATE INDEX idx_audit_request_id ON audit_logs(request_id);
CREATE INDEX idx_audit_correlation_id ON audit_logs(correlation_id);
CREATE INDEX idx_audit_business_impact ON audit_logs(business_impact);
CREATE INDEX idx_audit_data_classification ON audit_logs(data_classification);
CREATE INDEX idx_audit_execution_time ON audit_logs(execution_time);

-- Indexes for change details
CREATE INDEX idx_change_audit_id ON audit_log_changes(audit_id);
CREATE INDEX idx_change_field_name ON audit_log_changes(field_name);
CREATE INDEX idx_change_timestamp ON audit_log_changes(timestamp);
CREATE INDEX idx_change_sensitive ON audit_log_changes(is_sensitive);

-- Indexes for metrics
CREATE INDEX idx_metric_audit_id ON audit_log_metrics(audit_id);
CREATE INDEX idx_metric_name ON audit_log_metrics(metric_name);
CREATE INDEX idx_metric_violation ON audit_log_metrics(is_violation);

-- Indexes for business context
CREATE INDEX idx_context_audit_id ON audit_business_context(audit_id);
CREATE INDEX idx_context_process ON audit_business_context(business_process);
CREATE INDEX idx_context_risk ON audit_business_context(risk_level);

-- =========================================
-- 6. PARTITIONING FOR PERFORMANCE
-- =========================================
-- Create partitioned table for high-volume audit logs (Oracle 12c+)
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE audit_logs_partitioned (
            audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            action VARCHAR2(100) NOT NULL,
            entity VARCHAR2(100),
            entity_id VARCHAR2(100),
            entity_name VARCHAR2(255),
            target VARCHAR2(255),
            user_name VARCHAR2(100),
            user_role VARCHAR2(50),
            user_avatar VARCHAR2(500),
            details CLOB,
            changes CLOB,
            ip_address VARCHAR2(50),
            location VARCHAR2(255),
            device_type VARCHAR2(50),
            browser VARCHAR2(100),
            os VARCHAR2(100),
            session_id VARCHAR2(100),
            severity VARCHAR2(20) DEFAULT ''info'',
            metadata CLOB,
            timestamp TIMESTAMP NOT NULL,
            user_id NUMBER,
            gym_id NUMBER,
            method_name VARCHAR2(200),
            class_name VARCHAR2(200),
            execution_time NUMBER(10),
            request_id VARCHAR2(100),
            correlation_id VARCHAR2(100),
            business_impact VARCHAR2(50) DEFAULT ''low'',
            data_classification VARCHAR2(50) DEFAULT ''internal'',
            retention_period NUMBER(3) DEFAULT 365
        ) PARTITION BY RANGE (timestamp)
        INTERVAL (NUMTOYMINTERVAL(1, ''MONTH''))
        (
            PARTITION p_initial VALUES LESS THAN (TIMESTAMP ''2024-01-01 00:00:00'')
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- Table already exists
            RAISE;
        END IF;
END;
/

-- =========================================
-- 7. DATA RETENTION POLICIES
-- =========================================
-- Create procedure for automated data cleanup
CREATE OR REPLACE PROCEDURE cleanup_old_audit_logs (
    p_retention_days IN NUMBER DEFAULT 1095, -- 3 years default
    p_batch_size IN NUMBER DEFAULT 10000
) AS
    v_deleted_count NUMBER := 0;
    v_total_deleted NUMBER := 0;
BEGIN
    -- Delete old audit logs and related data in batches
    LOOP
        DELETE FROM audit_log_metrics
        WHERE audit_id IN (
            SELECT audit_id FROM audit_logs 
            WHERE timestamp < SYSTIMESTAMP - p_retention_days
            AND ROWNUM <= p_batch_size
        );
        
        DELETE FROM audit_log_changes
        WHERE audit_id IN (
            SELECT audit_id FROM audit_logs 
            WHERE timestamp < SYSTIMESTAMP - p_retention_days
            AND ROWNUM <= p_batch_size
        );
        
        DELETE FROM audit_business_context
        WHERE audit_id IN (
            SELECT audit_id FROM audit_logs 
            WHERE timestamp < SYSTIMESTAMP - p_retention_days
            AND ROWNUM <= p_batch_size
        );
        
        DELETE FROM audit_logs
        WHERE timestamp < SYSTIMESTAMP - p_retention_days
        AND ROWNUM <= p_batch_size;
        
        v_deleted_count := SQL%ROWCOUNT;
        v_total_deleted := v_total_deleted + v_deleted_count;
        
        EXIT WHEN v_deleted_count < p_batch_size;
        
        COMMIT;
    END LOOP;
    
    COMMIT;
    
    -- Log cleanup operation
    INSERT INTO audit_logs (
        action, entity, details, severity, timestamp, user_name, user_role
    ) VALUES (
        'CLEANUP', 'AuditLog', 
        'Cleaned up ' || v_total_deleted || ' old audit log records older than ' || p_retention_days || ' days',
        'info', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM'
    );
    
    COMMIT;
END;
/

-- =========================================
-- 8. ANALYTICS VIEWS
-- =========================================
-- Create view for audit analytics
CREATE OR REPLACE VIEW audit_analytics_summary AS
SELECT 
    TRUNC(timestamp) as log_date,
    action,
    entity,
    user_role,
    severity,
    COUNT(*) as log_count,
    COUNT(DISTINCT user_name) as unique_users,
    AVG(execution_time) as avg_execution_time,
    MAX(execution_time) as max_execution_time,
    COUNT(CASE WHEN severity IN ('high', 'critical') THEN 1 END) as critical_events,
    COUNT(CASE WHEN business_impact = 'high' THEN 1 END) as high_business_impact_events
FROM audit_logs
WHERE timestamp >= TRUNC(SYSTIMESTAMP) - 90 -- Last 90 days
GROUP BY TRUNC(timestamp), action, entity, user_role, severity;

-- Create view for change analytics
CREATE OR REPLACE VIEW audit_change_analytics AS
SELECT 
    TRUNC(alc.timestamp) as change_date,
    al.action,
    al.entity,
    alc.field_name,
    alc.change_type,
    alc.is_sensitive,
    COUNT(*) as change_count,
    COUNT(DISTINCT al.user_name) as unique_users
FROM audit_log_changes alc
JOIN audit_logs al ON alc.audit_id = al.audit_id
WHERE alc.timestamp >= TRUNC(SYSTIMESTAMP) - 90 -- Last 90 days
GROUP BY TRUNC(alc.timestamp), al.action, al.entity, alc.field_name, alc.change_type, alc.is_sensitive;

-- =========================================
-- 9. SECURITY CONFIGURATION
-- =========================================
-- Create audit policy for sensitive operations
CREATE OR REPLACE TRIGGER trg_audit_sensitive_operations
    AFTER INSERT OR UPDATE OR DELETE ON audit_logs
    FOR EACH ROW
DECLARE
    v_is_sensitive CHAR(1) := 'N';
BEGIN
    -- Mark as sensitive if high severity or specific actions
    IF :NEW.severity IN ('high', 'critical') OR 
       :NEW.action IN ('PASSWORD_CHANGE', 'PERMISSION_CHANGE', 'SECURITY_ALERT') OR
       :NEW.entity IN ('Security', 'User', 'Role') THEN
        v_is_sensitive := 'Y';
    END IF;
    
    -- Additional sensitive data classification
    IF v_is_sensitive = 'Y' THEN
        :NEW.data_classification := 'confidential';
        :NEW.retention_period := 2555; -- 7 years for compliance
    END IF;
END;
/

-- =========================================
-- 10. INITIAL DATA SEEDING
-- =========================================
-- Log the system upgrade
INSERT INTO audit_logs (
    action, entity, details, severity, timestamp, user_name, user_role, 
    method_name, class_name, business_impact, data_classification
) VALUES (
    'SYSTEM_UPGRADE', 'AuditSystem', 
    'Enhanced audit logging system deployed with micro-level tracking capabilities',
    'info', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM',
    'deploy', 'DatabaseMigration', 'high', 'system'
);

COMMIT;