CREATE TABLE equipment_maintenance (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id NUMBER(19,0) NOT NULL,
    maintenance_type VARCHAR2(255) NOT NULL,
    description CLOB,
    technician_name VARCHAR2(255),
    vendor VARCHAR2(255),
    cost NUMBER(19,2),
    maintenance_date DATE,
    next_due_date DATE,
    status VARCHAR2(255) NOT NULL,
    document_url VARCHAR2(255),
    created_at TIMESTAMP,
    CONSTRAINT fk_maintenance_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id) ON DELETE CASCADE
);

CREATE INDEX idx_maintenance_equipment ON equipment_maintenance(equipment_id);
CREATE INDEX idx_maintenance_status ON equipment_maintenance(status);
CREATE INDEX idx_maintenance_date ON equipment_maintenance(maintenance_date);
