CREATE TABLE feature_flags (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    feature_key VARCHAR2(100) NOT NULL UNIQUE,
    enabled NUMBER(1) NOT NULL DEFAULT 0,
    description VARCHAR2(500),
    allowed_roles VARCHAR2(255),
    updated_at TIMESTAMP,
    CONSTRAINT pk_feature_flags PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_feature_flags_key ON feature_flags(feature_key);

INSERT INTO feature_flags (feature_key, enabled, description, allowed_roles, updated_at)
VALUES ('feedback_widget', 0, 'Global feedback widget toggle', 'ADMIN,OWNER,TRAINER,MEMBER', SYSTIMESTAMP);

INSERT INTO feature_flags (feature_key, enabled, description, allowed_roles, updated_at)
VALUES ('beta_mode', 0, 'Enable beta-specific features', 'ADMIN,OWNER', SYSTIMESTAMP);

INSERT INTO feature_flags (feature_key, enabled, description, allowed_roles, updated_at)
VALUES ('new_ui', 0, 'New UI/UX improvements', 'ADMIN', SYSTIMESTAMP);

INSERT INTO feature_flags (feature_key, enabled, description, allowed_roles, updated_at)
VALUES ('debug_mode', 0, 'Developer debug information', 'ADMIN', SYSTIMESTAMP);