-- =========================================
-- V9__create_role_permissions_table.sql
-- Create role permissions mapping table
-- =========================================

-- Create role_permissions table
BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE role_permissions (
            permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            role VARCHAR2(20) NOT NULL,
            permission VARCHAR2(50) NOT NULL,
            scope VARCHAR2(100),
            is_active NUMBER(1) DEFAULT 1,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT uk_role_permission UNIQUE (role, permission, scope),
            CONSTRAINT chk_role_permission_role CHECK (role IN (''OWNER'', ''ADMIN'', ''TRAINER'', ''MEMBER'')),
            CONSTRAINT chk_role_permission_active CHECK (is_active IN (0, 1))
        )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            NULL; -- Table already exists, skip
        ELSE
            RAISE;
        END IF;
END;
/

-- Create indexes
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_rp_role ON role_permissions(role)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            NULL; -- Index already exists, skip
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_rp_permission ON role_permissions(permission)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            NULL; -- Index already exists, skip
        ELSE
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX idx_rp_active ON role_permissions(is_active)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN
            NULL; -- Index already exists, skip
        ELSE
            RAISE;
        END IF;
END;
/

-- Insert default permissions for OWNER role
INSERT INTO role_permissions (role, permission) VALUES 
('OWNER', 'USER_VIEW'),
('OWNER', 'USER_CREATE'),
('OWNER', 'USER_UPDATE'),
('OWNER', 'USER_DELETE'),
('OWNER', 'USER_ASSIGN_ROLES'),
('OWNER', 'GYM_VIEW'),
('OWNER', 'GYM_CREATE'),
('OWNER', 'GYM_UPDATE'),
('OWNER', 'GYM_DELETE'),
('OWNER', 'GYM_MANAGE_SETTINGS'),
('OWNER', 'MEMBER_VIEW'),
('OWNER', 'MEMBER_CREATE'),
('OWNER', 'MEMBER_UPDATE'),
('OWNER', 'MEMBER_DELETE'),
('OWNER', 'MEMBER_MANAGE_MEMBERSHIP'),
('OWNER', 'TRAINER_VIEW'),
('OWNER', 'TRAINER_CREATE'),
('OWNER', 'TRAINER_UPDATE'),
('OWNER', 'TRAINER_DELETE'),
('OWNER', 'TRAINER_ASSIGN_CUSTOMERS'),
('OWNER', 'SESSION_VIEW'),
('OWNER', 'SESSION_CREATE'),
('OWNER', 'SESSION_UPDATE'),
('OWNER', 'SESSION_DELETE'),
('OWNER', 'SESSION_MANAGE_OWN'),
('OWNER', 'STAFF_VIEW'),
('OWNER', 'STAFF_CREATE'),
('OWNER', 'STAFF_UPDATE'),
('OWNER', 'STAFF_DELETE'),
('OWNER', 'STAFF_MANAGE_SHIFTS'),
('OWNER', 'PERFORMANCE_VIEW'),
('OWNER', 'PERFORMANCE_MANAGE'),
('OWNER', 'ANALYTICS_VIEW'),
('OWNER', 'REPORTS_GENERATE'),
('OWNER', 'BILLING_VIEW'),
('OWNER', 'BILLING_MANAGE'),
('OWNER', 'PAYMENTS_PROCESS'),
('OWNER', 'REFUNDS_PROCESS'),
('OWNER', 'SYSTEM_SETTINGS'),
('OWNER', 'SYSTEM_BACKUP'),
('OWNER', 'AUDIT_VIEW'),
('OWNER', 'MAINTENANCE_MODE'),
('OWNER', 'NOTIFICATIONS_SEND'),
('OWNER', 'EMAIL_SEND'),
('OWNER', 'ANNOUNCEMENTS_CREATE'),
('OWNER', 'EQUIPMENT_VIEW'),
('OWNER', 'EQUIPMENT_CREATE'),
('OWNER', 'EQUIPMENT_UPDATE'),
('OWNER', 'EQUIPMENT_DELETE'),
('OWNER', 'EQUIPMENT_MAINTENANCE');

-- Insert permissions for ADMIN role
INSERT INTO role_permissions (role, permission) VALUES 
('ADMIN', 'USER_VIEW'),
('ADMIN', 'USER_CREATE'),
('ADMIN', 'USER_UPDATE'),
('ADMIN', 'USER_ASSIGN_ROLES'),
('ADMIN', 'GYM_VIEW'),
('ADMIN', 'GYM_UPDATE'),
('ADMIN', 'GYM_MANAGE_SETTINGS'),
('ADMIN', 'MEMBER_VIEW'),
('ADMIN', 'MEMBER_CREATE'),
('ADMIN', 'MEMBER_UPDATE'),
('ADMIN', 'MEMBER_DELETE'),
('ADMIN', 'MEMBER_MANAGE_MEMBERSHIP'),
('ADMIN', 'TRAINER_VIEW'),
('ADMIN', 'TRAINER_CREATE'),
('ADMIN', 'TRAINER_UPDATE'),
('ADMIN', 'TRAINER_DELETE'),
('ADMIN', 'TRAINER_ASSIGN_CUSTOMERS'),
('ADMIN', 'SESSION_VIEW'),
('ADMIN', 'SESSION_CREATE'),
('ADMIN', 'SESSION_UPDATE'),
('ADMIN', 'SESSION_DELETE'),
('ADMIN', 'STAFF_VIEW'),
('ADMIN', 'STAFF_CREATE'),
('ADMIN', 'STAFF_UPDATE'),
('ADMIN', 'STAFF_DELETE'),
('ADMIN', 'STAFF_MANAGE_SHIFTS'),
('ADMIN', 'PERFORMANCE_VIEW'),
('ADMIN', 'PERFORMANCE_MANAGE'),
('ADMIN', 'ANALYTICS_VIEW'),
('ADMIN', 'REPORTS_GENERATE'),
('ADMIN', 'BILLING_VIEW'),
('ADMIN', 'BILLING_MANAGE'),
('ADMIN', 'PAYMENTS_PROCESS'),
('ADMIN', 'REFUNDS_PROCESS'),
('ADMIN', 'NOTIFICATIONS_SEND'),
('ADMIN', 'EMAIL_SEND'),
('ADMIN', 'ANNOUNCEMENTS_CREATE'),
('ADMIN', 'EQUIPMENT_VIEW'),
('ADMIN', 'EQUIPMENT_CREATE'),
('ADMIN', 'EQUIPMENT_UPDATE'),
('ADMIN', 'EQUIPMENT_DELETE'),
('ADMIN', 'EQUIPMENT_MAINTENANCE');

-- Insert permissions for TRAINER role
INSERT INTO role_permissions (role, permission) VALUES 
('TRAINER', 'USER_VIEW'),
('TRAINER', 'USER_UPDATE'),
('TRAINER', 'MEMBER_VIEW'),
('TRAINER', 'MEMBER_UPDATE'),
('TRAINER', 'SESSION_VIEW'),
('TRAINER', 'SESSION_CREATE'),
('TRAINER', 'SESSION_UPDATE'),
('TRAINER', 'SESSION_DELETE'),
('TRAINER', 'SESSION_MANAGE_OWN'),
('TRAINER', 'PERFORMANCE_VIEW'),
('TRAINER', 'NOTIFICATIONS_SEND'),
('TRAINER', 'EMAIL_SEND'),
('TRAINER', 'EQUIPMENT_VIEW');

-- Insert permissions for MEMBER role
INSERT INTO role_permissions (role, permission) VALUES 
('MEMBER', 'USER_VIEW'),
('MEMBER', 'USER_UPDATE'),
('MEMBER', 'SESSION_VIEW'),
('MEMBER', 'SESSION_MANAGE_OWN'),
('MEMBER', 'BILLING_VIEW'),
('MEMBER', 'EQUIPMENT_VIEW');

COMMIT;
