-- ==========================================
-- FIX MISSING GYMS AND MEMBERSHIPS TABLES
-- ==========================================

-- 1. Create GYMS table if not exists
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'GYMS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE gyms (
        gym_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name VARCHAR2(100) NOT NULL,
        address VARCHAR2(255),
        phone VARCHAR2(20),
        email VARCHAR2(100),
        website VARCHAR2(100),
        subscription_plan VARCHAR2(50) DEFAULT ''FREE'',
        invite_code VARCHAR2(20) UNIQUE
      )';
  END IF;
END;
/

-- Ensure Gym Exists (Safe Merge/Insert)
DECLARE
  v_count NUMBER;
BEGIN
    SELECT count(*) INTO v_count FROM gyms WHERE name = 'AthlonX Main';
    IF v_count = 0 THEN
        INSERT INTO gyms (name, address, invite_code) VALUES ('AthlonX Main', '123 Fitness Blvd', 'ATHLONX-001');
    END IF;
    COMMIT;
END;
/

-- 2. Create MEMBERSHIPS table if not exists
DECLARE
  v_count NUMBER;
BEGIN
  SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'MEMBERSHIPS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE memberships (
        membership_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        gym_id NUMBER NOT NULL,
        package_id NUMBER,
        start_date DATE,
        end_date DATE,
        status VARCHAR2(20) DEFAULT ''ACTIVE'',
        payment_status VARCHAR2(20) DEFAULT ''PAID'',
        auto_renew NUMBER(1) DEFAULT 0,
        CONSTRAINT fk_mem_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
        CONSTRAINT fk_mem_gym FOREIGN KEY (gym_id) REFERENCES gyms(gym_id) ON DELETE CASCADE
      )';
  END IF;
END;
/

-- ==========================================
-- SEED DATA (SAFE UPSERT)
-- ==========================================

DECLARE
    v_gym_id NUMBER;
    v_pkg_basic NUMBER;
    v_pkg_proto NUMBER;
    v_user_alice NUMBER;
    v_user_bob NUMBER;
    v_user_charlie NUMBER;
    v_user_david NUMBER;
    v_user_eve NUMBER;
    v_user_frank NUMBER;
    v_user_grace NUMBER;
BEGIN
    -- Get Main Gym ID
    SELECT gym_id INTO v_gym_id FROM gyms WHERE name = 'AthlonX Main' FETCH FIRST 1 ROWS ONLY;

    -- Ensure Membership Packages exist (Simulating if not present)
    -- Ideally these should be in membership_packages table, but for now we rely on IDs or assume they exist.
    -- We will just use placeholders 1, 2, 3 assuming standard setup.
    -- If you need specific packages, ensure they are in migration_v2.

    -- ====================================================================================
    -- BULK POPULATION: Ensure ALL Customers have a plan (Catch-all)
    -- ====================================================================================
    -- ====================================================================================
    -- STRICT DATA CORRELATION: Ensure Dates, Duration, and Status align perfectly
    -- ====================================================================================
    DECLARE
        v_user_id NUMBER;
        v_pkg_id NUMBER;
        v_duration_months NUMBER;
        v_stat VARCHAR2(20);
        v_start DATE;
        v_end DATE;
        v_random_offset NUMBER;
    BEGIN
        FOR r IN (
            SELECT user_id 
            FROM users u
            WHERE u.user_id IN (
                SELECT map.user_id 
                FROM user_role_map map
                JOIN roles r ON map.role_id = r.role_id
                WHERE r.role_name = 'CUSTOMER'
            )
        ) LOOP
            -- Determine Package and Duration
            v_pkg_id := MOD(r.user_id, 4) + 1;
            
            CASE v_pkg_id
                WHEN 4 THEN v_duration_months := 12; -- Annual
                ELSE v_duration_months := 1;         -- Monthly
            END CASE;

            -- Calculate Dates and Status
            -- We want a mix: mostly Active, some Expired.
            -- Let's generalize: Start date is random day between -400 days and +10 days.
            v_random_offset := MOD(r.user_id * 17, 400) - 350; -- Bias towards past
            v_start := TRUNC(SYSDATE) + v_random_offset;
            v_end := ADD_MONTHS(v_start, v_duration_months);

            IF v_end < TRUNC(SYSDATE) THEN
                v_stat := 'EXPIRED';
            ELSIF v_start > TRUNC(SYSDATE) THEN
                v_stat := 'PENDING'; -- Future start
            ELSE
                v_stat := 'ACTIVE';
            END IF;
            
            -- DELETE existing to ensure clean state
            DELETE FROM memberships WHERE user_id = r.user_id;

            INSERT INTO memberships (user_id, gym_id, package_id, start_date, end_date, status)
            VALUES (r.user_id, v_gym_id, v_pkg_id, v_start, v_end, v_stat);
        END LOOP;
        
        COMMIT;
    END;

    COMMIT;
END;
/
EXIT;
