-- AthlonX Gym Management System v2 Migration Script
-- Adds PT Scheduling, Staff Performance, Settings, and Package Management
-- Run this script after the base schema.sql

-- ============================================================================
-- 1. PT SESSIONS TABLE
-- ============================================================================
CREATE TABLE pt_sessions (
    session_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id NUMBER NOT NULL,
    member_id NUMBER NOT NULL,
    session_date TIMESTAMP NOT NULL,
    duration_minutes NUMBER NOT NULL,
    status VARCHAR2(20) NOT NULL,
    progress_notes CLOB,
    workout_plan CLOB,
    diet_plan CLOB,
    is_recurring NUMBER(1) DEFAULT 0,
    recurring_frequency VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pts_trainer FOREIGN KEY (trainer_id) REFERENCES users(user_id),
    CONSTRAINT fk_pts_member FOREIGN KEY (member_id) REFERENCES users(user_id),
    CONSTRAINT chk_pts_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'MISSED', 'CANCELLED')),
    CONSTRAINT chk_pts_recurring CHECK (is_recurring IN (0, 1)),
    CONSTRAINT chk_pts_duration CHECK (duration_minutes > 0)
);

-- Indexes for performance optimization
CREATE INDEX idx_pts_trainer ON pt_sessions(trainer_id);
CREATE INDEX idx_pts_member ON pt_sessions(member_id);
CREATE INDEX idx_pts_date ON pt_sessions(session_date);
CREATE INDEX idx_pts_status ON pt_sessions(status);

-- ============================================================================
-- 2. STAFF PERFORMANCE TABLE
-- ============================================================================
CREATE TABLE staff_performance (
    performance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id NUMBER NOT NULL,
    sessions_completed NUMBER DEFAULT 0,
    attendance_rate NUMBER(5,2),
    satisfaction_score NUMBER(3,2),
    present_days NUMBER DEFAULT 0,
    absent_days NUMBER DEFAULT 0,
    late_days NUMBER DEFAULT 0,
    record_month VARCHAR2(7) NOT NULL, -- Format: YYYY-MM
    CONSTRAINT fk_sp_staff FOREIGN KEY (staff_id) REFERENCES users(user_id),
    CONSTRAINT uk_staff_month UNIQUE (staff_id, record_month),
    CONSTRAINT chk_sp_attendance CHECK (attendance_rate >= 0 AND attendance_rate <= 100),
    CONSTRAINT chk_sp_satisfaction CHECK (satisfaction_score >= 0 AND satisfaction_score <= 5)
);

-- Index for performance queries
CREATE INDEX idx_sp_staff ON staff_performance(staff_id);
CREATE INDEX idx_sp_month ON staff_performance(record_month);

-- ============================================================================
-- 3. STAFF SHIFTS TABLE
-- ============================================================================
CREATE TABLE staff_shifts (
    shift_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id NUMBER NOT NULL,
    shift_date DATE NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'SCHEDULED',
    CONSTRAINT fk_ss_staff FOREIGN KEY (staff_id) REFERENCES users(user_id),
    CONSTRAINT chk_ss_status CHECK (status IN ('SCHEDULED', 'COMPLETED', 'MISSED')),
    CONSTRAINT chk_ss_times CHECK (end_time > start_time)
);

-- Indexes for shift queries
CREATE INDEX idx_ss_staff ON staff_shifts(staff_id);
CREATE INDEX idx_ss_date ON staff_shifts(shift_date);

-- ============================================================================
-- 4. GYM SETTINGS TABLE
-- ============================================================================
CREATE TABLE gym_settings (
    setting_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR2(100) NOT NULL UNIQUE,
    setting_value CLOB NOT NULL,
    setting_type VARCHAR2(50) NOT NULL
);

-- Index for settings lookup
CREATE INDEX idx_gs_type ON gym_settings(setting_type);

-- ============================================================================
-- 5. MEMBERSHIP PACKAGES TABLE
-- ============================================================================
CREATE TABLE membership_packages (
    package_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_name VARCHAR2(100) NOT NULL,
    price NUMBER(10,2) NOT NULL,
    duration_days NUMBER NOT NULL,
    included_pt_sessions NUMBER DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1,
    CONSTRAINT chk_mp_price CHECK (price >= 0),
    CONSTRAINT chk_mp_duration CHECK (duration_days > 0),
    CONSTRAINT chk_mp_sessions CHECK (included_pt_sessions >= 0),
    CONSTRAINT chk_mp_active CHECK (is_active IN (0, 1))
);

-- Index for active packages
CREATE INDEX idx_mp_active ON membership_packages(is_active);

-- ============================================================================
-- 6. BLACKOUT DAYS TABLE
-- ============================================================================
CREATE TABLE blackout_days (
    blackout_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blackout_date DATE NOT NULL UNIQUE,
    reason VARCHAR2(255)
);

-- Index for date lookups
CREATE INDEX idx_bd_date ON blackout_days(blackout_date);

-- ============================================================================
-- SEED DATA FOR NEW TABLES
-- ============================================================================

-- Default Gym Settings
INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('gym_hours_monday', '{"open": "06:00", "close": "22:00"}', 'GYM_HOURS');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('gym_hours_tuesday', '{"open": "06:00", "close": "22:00"}', 'GYM_HOURS');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('gym_hours_wednesday', '{"open": "06:00", "close": "22:00"}', 'GYM_HOURS');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('gym_hours_thursday', '{"open": "06:00", "close": "22:00"}', 'GYM_HOURS');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('gym_hours_friday', '{"open": "06:00", "close": "22:00"}', 'GYM_HOURS');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('gym_hours_saturday', '{"open": "08:00", "close": "20:00"}', 'GYM_HOURS');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('gym_hours_sunday', '{"open": "08:00", "close": "20:00"}', 'GYM_HOURS');

-- PT Configuration Settings
INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('pt_default_duration', '60', 'PT_CONFIG');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('pt_max_sessions_per_day', '8', 'PT_CONFIG');

INSERT INTO gym_settings (setting_key, setting_value, setting_type) 
VALUES ('pt_slot_interval', '30', 'PT_CONFIG');

-- Sample Membership Packages
INSERT INTO membership_packages (package_name, price, duration_days, included_pt_sessions, is_active)
VALUES ('Basic Monthly', 49.99, 30, 0, 1);

INSERT INTO membership_packages (package_name, price, duration_days, included_pt_sessions, is_active)
VALUES ('Standard Monthly', 79.99, 30, 4, 1);

INSERT INTO membership_packages (package_name, price, duration_days, included_pt_sessions, is_active)
VALUES ('Premium Monthly', 129.99, 30, 8, 1);

INSERT INTO membership_packages (package_name, price, duration_days, included_pt_sessions, is_active)
VALUES ('Annual Basic', 499.99, 365, 0, 1);

INSERT INTO membership_packages (package_name, price, duration_days, included_pt_sessions, is_active)
VALUES ('Annual Premium', 1299.99, 365, 96, 1);

-- Sample PT Sessions (using existing users from base schema)
-- Mike (trainer_id=2) with Alice (member_id=5)
INSERT INTO pt_sessions (trainer_id, member_id, session_date, duration_minutes, status, is_recurring)
VALUES (2, 5, TIMESTAMP '2024-12-10 09:00:00', 60, 'COMPLETED', 0);

INSERT INTO pt_sessions (trainer_id, member_id, session_date, duration_minutes, status, progress_notes, is_recurring)
VALUES (2, 5, TIMESTAMP '2024-12-12 09:00:00', 60, 'COMPLETED', 'Great progress on squats. Increased weight by 10kg.', 0);

INSERT INTO pt_sessions (trainer_id, member_id, session_date, duration_minutes, status, is_recurring)
VALUES (2, 5, TIMESTAMP '2024-12-15 09:00:00', 60, 'SCHEDULED', 0);

-- Sarah (trainer_id=3) with Charlie (member_id=7)
INSERT INTO pt_sessions (trainer_id, member_id, session_date, duration_minutes, status, is_recurring)
VALUES (3, 7, TIMESTAMP '2024-12-11 14:00:00', 60, 'COMPLETED', 0);

INSERT INTO pt_sessions (trainer_id, member_id, session_date, duration_minutes, status, is_recurring)
VALUES (3, 7, TIMESTAMP '2024-12-16 14:00:00', 60, 'SCHEDULED', 0);

-- Rocky (trainer_id=9) with David (member_id=11)
INSERT INTO pt_sessions (trainer_id, member_id, session_date, duration_minutes, status, is_recurring)
VALUES (9, 11, TIMESTAMP '2024-12-13 10:00:00', 60, 'SCHEDULED', 0);

-- Sample Staff Performance Data
-- Mike (staff_id=2) - December 2024
INSERT INTO staff_performance (staff_id, sessions_completed, attendance_rate, satisfaction_score, present_days, absent_days, late_days, record_month)
VALUES (2, 45, 95.00, 4.8, 19, 1, 0, '2024-12');

-- Sarah (staff_id=3) - December 2024
INSERT INTO staff_performance (staff_id, sessions_completed, attendance_rate, satisfaction_score, present_days, absent_days, late_days, record_month)
VALUES (3, 38, 100.00, 4.9, 20, 0, 0, '2024-12');

-- Jim (staff_id=4) - December 2024
INSERT INTO staff_performance (staff_id, sessions_completed, attendance_rate, satisfaction_score, present_days, absent_days, late_days, record_month)
VALUES (4, 0, 90.00, 4.5, 18, 2, 1, '2024-12');

-- Rocky (staff_id=9) - December 2024
INSERT INTO staff_performance (staff_id, sessions_completed, attendance_rate, satisfaction_score, present_days, absent_days, late_days, record_month)
VALUES (9, 52, 98.00, 4.7, 20, 0, 1, '2024-12');

-- Sample Staff Shifts
-- Mike's shifts for next week
INSERT INTO staff_shifts (staff_id, shift_date, start_time, end_time, status)
VALUES (2, DATE '2024-12-16', TIMESTAMP '2024-12-16 08:00:00', TIMESTAMP '2024-12-16 16:00:00', 'SCHEDULED');

INSERT INTO staff_shifts (staff_id, shift_date, start_time, end_time, status)
VALUES (2, DATE '2024-12-17', TIMESTAMP '2024-12-17 08:00:00', TIMESTAMP '2024-12-17 16:00:00', 'SCHEDULED');

-- Sarah's shifts
INSERT INTO staff_shifts (staff_id, shift_date, start_time, end_time, status)
VALUES (3, DATE '2024-12-16', TIMESTAMP '2024-12-16 12:00:00', TIMESTAMP '2024-12-16 20:00:00', 'SCHEDULED');

INSERT INTO staff_shifts (staff_id, shift_date, start_time, end_time, status)
VALUES (3, DATE '2024-12-17', TIMESTAMP '2024-12-17 12:00:00', TIMESTAMP '2024-12-17 20:00:00', 'SCHEDULED');

-- Sample Blackout Days
INSERT INTO blackout_days (blackout_date, reason)
VALUES (DATE '2024-12-25', 'Christmas Day');

INSERT INTO blackout_days (blackout_date, reason)
VALUES (DATE '2025-01-01', 'New Year''s Day');

INSERT INTO blackout_days (blackout_date, reason)
VALUES (DATE '2025-07-04', 'Independence Day');

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run these to verify the migration was successful

-- Check table creation
SELECT table_name FROM user_tables WHERE table_name IN (
    'PT_SESSIONS', 
    'STAFF_PERFORMANCE', 
    'STAFF_SHIFTS', 
    'GYM_SETTINGS', 
    'MEMBERSHIP_PACKAGES', 
    'BLACKOUT_DAYS'
) ORDER BY table_name;

-- Check row counts
SELECT 'PT_SESSIONS' as table_name, COUNT(*) as row_count FROM pt_sessions
UNION ALL
SELECT 'STAFF_PERFORMANCE', COUNT(*) FROM staff_performance
UNION ALL
SELECT 'STAFF_SHIFTS', COUNT(*) FROM staff_shifts
UNION ALL
SELECT 'GYM_SETTINGS', COUNT(*) FROM gym_settings
UNION ALL
SELECT 'MEMBERSHIP_PACKAGES', COUNT(*) FROM membership_packages
UNION ALL
SELECT 'BLACKOUT_DAYS', COUNT(*) FROM blackout_days;

-- Check indexes
SELECT index_name, table_name FROM user_indexes 
WHERE table_name IN (
    'PT_SESSIONS', 
    'STAFF_PERFORMANCE', 
    'STAFF_SHIFTS', 
    'GYM_SETTINGS', 
    'MEMBERSHIP_PACKAGES', 
    'BLACKOUT_DAYS'
)
ORDER BY table_name, index_name;
