-- Gym Management System v1 Schema Script
-- Run this script in Oracle SQL Developer or SQLPlus

-- 1. Clean up (Optional - uncomment if you want to reset)
-- DROP TABLE trainer_customer_map;
-- DROP TABLE user_role_map;
-- DROP TABLE users;
-- DROP TABLE roles;

-- 2. Create ROLES Table
CREATE TABLE roles (
    role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR2(50) NOT NULL UNIQUE
);

-- 3. Create USERS Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL, -- In a real app, this should be BCrypt encoded
    full_name VARCHAR2(100),
    email VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Create USER_ROLE_MAP Table
CREATE TABLE user_role_map (
    map_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT fk_urm_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_urm_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

-- 5. Create TRAINER_CUSTOMER_MAP Table
CREATE TABLE trainer_customer_map (
    map_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_user_id NUMBER NOT NULL,
    customer_user_id NUMBER NOT NULL,
    CONSTRAINT fk_tcm_trainer FOREIGN KEY (trainer_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_tcm_customer FOREIGN KEY (customer_user_id) REFERENCES users(user_id)
);

-- 6. Seed Data: Roles
INSERT INTO roles (role_name) VALUES ('OWNER');
INSERT INTO roles (role_name) VALUES ('TRAINER');
INSERT INTO roles (role_name) VALUES ('STAFF');
INSERT INTO roles (role_name) VALUES ('CUSTOMER');

-- 7. Seed Data: Users
-- Password 'pass123' for all (for v1 demo purposes)
INSERT INTO users (username, password, full_name, email) VALUES ('admin', 'pass123', 'John Owner', 'owner@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('mike.tyson', 'pass123', 'Mike Tyson', 'mike.tyson@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('sarah.connor', 'pass123', 'Sarah Connor', 'sarah.connor@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('jim.halpert', 'pass123', 'Jim Halpert', 'jim.halpert@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('alice.smith', 'pass123', 'Alice Smith', 'alice.smith@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('bob.jones', 'pass123', 'Bob Jones', 'bob.jones@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('charlie.brown', 'pass123', 'Charlie Brown', 'charlie.brown@gym.com');

-- 8. Seed Data: User Role Mappings
-- Assuming IDs: 1=admin, 2=trainer1, 3=trainer2, 4=staff1, 5=cust1, 6=cust2, 7=cust3
-- Roles: 1=OWNER, 2=TRAINER, 3=STAFF, 4=CUSTOMER
INSERT INTO user_role_map (user_id, role_id) VALUES (1, 1); -- John is Owner
INSERT INTO user_role_map (user_id, role_id) VALUES (2, 2); -- Mike is Trainer
INSERT INTO user_role_map (user_id, role_id) VALUES (3, 2); -- Sarah is Trainer
INSERT INTO user_role_map (user_id, role_id) VALUES (4, 3); -- Jim is Staff
INSERT INTO user_role_map (user_id, role_id) VALUES (5, 4); -- Alice is Customer
INSERT INTO user_role_map (user_id, role_id) VALUES (6, 4); -- Bob is Customer
INSERT INTO user_role_map (user_id, role_id) VALUES (7, 4); -- Charlie is Customer

-- 9. Seed Data: Trainer Customer Mappings
-- Mike (2) trains Alice (5) and Bob (6)
INSERT INTO trainer_customer_map (trainer_user_id, customer_user_id) VALUES (2, 5);
INSERT INTO trainer_customer_map (trainer_user_id, customer_user_id) VALUES (2, 6);

-- Sarah (3) trains Charlie (7)
INSERT INTO trainer_customer_map (trainer_user_id, customer_user_id) VALUES (3, 7);

-- Additional Seed Data
-- New Users
INSERT INTO users (username, password, full_name, email) VALUES ('jane.doe', 'pass123', 'Jane Doe', 'jane.doe@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('rocky.balboa', 'pass123', 'Rocky Balboa', 'rocky.balboa@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('pam.beesly', 'pass123', 'Pam Beesly', 'pam.beesly@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('david.beckham', 'pass123', 'David Beckham', 'david.beckham@gym.com');
INSERT INTO users (username, password, full_name, email) VALUES ('serena.williams', 'pass123', 'Serena Williams', 'serena.williams@gym.com');

-- New User Role Mappings
-- IDs: 8=owner2, 9=trainer3, 10=staff2, 11=cust4, 12=cust5
INSERT INTO user_role_map (user_id, role_id) VALUES (8, 1); -- Jane is Owner
INSERT INTO user_role_map (user_id, role_id) VALUES (9, 2); -- Rocky is Trainer
INSERT INTO user_role_map (user_id, role_id) VALUES (10, 3); -- Pam is Staff
INSERT INTO user_role_map (user_id, role_id) VALUES (11, 4); -- David is Customer
INSERT INTO user_role_map (user_id, role_id) VALUES (12, 4); -- Serena is Customer

-- New Trainer Customer Mappings
-- Rocky (9) trains David (11) and Serena (12)
INSERT INTO trainer_customer_map (trainer_user_id, customer_user_id) VALUES (9, 11);
INSERT INTO trainer_customer_map (trainer_user_id, customer_user_id) VALUES (9, 12);

-- Mike (2) also trains David (11) - Shared customer example
INSERT INTO trainer_customer_map (trainer_user_id, customer_user_id) VALUES (2, 11);

COMMIT;
